#!/usr/bin/env python3
"""Generate src/game/PlayerFix.hpp from Geode's GeometryDash.bro.

Copies every gameplay-relevant PlayerObject field so a checkpoint restore brings
back the exact player state (GD's own checkpoints skip some fields). Rendering
objects (sprites, particles, streaks) are skipped. Re-run after updating bindings:
    python3 tools/gen_player_fix.py path/to/bindings/2.2081/GeometryDash.bro
"""
import re, sys
bro = sys.argv[1]
out = sys.argv[2] if len(sys.argv) > 2 else "src/game/PlayerFix.hpp"
lines = open(bro, encoding="utf-8").read().split("\n")
start = next(i for i, l in enumerate(lines) if l.startswith("class PlayerObject "))
ALLOWED = {
    "bool", "int", "float", "double", "unsigned char", "cocos2d::CCPoint",
    "GameObject*", "DashRingObject*", "gd::map<int, bool>", "gd::unordered_set<int>",
    "gd::vector<float>", "gd::unordered_map<int, GJPointDouble>",
    "gd::unordered_map<int, GameObject*>", "geode::SeedValueRSV",
}
fields, block = [], None
for raw in lines[start + 1:]:
    t = raw.strip()
    if re.match(r"^[a-z0-9, ]+\{$", t) and "(" not in t:
        block = t; continue
    if t == "}" and block:
        block = None; continue
    if t == "}":
        break
    if "(" in t or not t.endswith(";") or t.startswith("//"):
        continue
    if block and "win" not in block:
        continue  # member does not exist on Windows
    m = re.match(r"(.+?)\s*(m_\w+|unk\w*)\s*;$", t)
    if not m or m.group(1).strip() not in ALLOWED:
        continue
    fields.append(m.group(2))
body = ["// GENERATED by tools/gen_player_fix.py from Geode bindings (GD 2.2081). Do not edit by hand.",
        "#pragma once", "#include <Geode/Geode.hpp>", "", "namespace rpf::game {", "",
        "struct PlayerFix {"]
body += [f"    decltype(PlayerObject::{f}) {f};" for f in fields]
body += ["", "    void save(PlayerObject* p) {"] + [f"        {f} = p->{f};" for f in fields] + ["    }"]
body += ["    void load(PlayerObject* p) const {"] + [f"        p->{f} = {f};" for f in fields] + ["    }", "};", "", "} // namespace rpf::game", ""]
open(out, "w", encoding="utf-8").write("\n".join(body))
print(f"{len(fields)} fields -> {out}")
