name: Build Real Pathfinder

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          bindings-ref: d641858f3e1cd2c6d86013c799f224ebdb8ec1cd
          target: Win64

      - name: Upload the mod
        uses: actions/upload-artifact@v4
        with:
          name: Real Pathfinder
          path: ${{ steps.build.outputs.build-output }}
